[package]
name = "direct3d"
version = "0.1.0"
authors = ["Gabriel Majeri <gabriel.majeri6@gmail.com>"]

[target.'cfg(windows)'.dependencies]
common = { path = "../common" }
dxgi = { path = "../dxgi" }

[target.'cfg(windows)'.dev-dependencies]
winit = "*"
