[package]
name = "direct2d"
version = "0.1.0"
authors = ["Gabriel Majeri <gabriel.majeri6@gmail.com>"]

[target.'cfg(windows)'.dependencies]
common = { path = ".." }
direct3d = { path = "../direct3d" }
